print("Bài 2: VS Code")
print("VS Code là một phần mềm mã nguồn mở")
print("-" * 30)
print("Một vài text editor khác có chức năng tương tự VS Code là: Eclipse, Sublime Text, ...")
print("-" * 30)
print("Giải thích meme: Text Editor đáng cài nhất chính là VS Code không phải là VI")
print("-" * 30)
