print('a. Chúng không được có khoảng trắng.')
print('   Chúng chỉ có thể bao gồm các chữ cái, số và dấu gạch dưới.')
print('   Chúng phải bắt đầu bằng một chữ cái hoặc dấu gạch dưới.')
print('   Sau đó, để tạo biến, bạn cần sử dụng dấu = để gán giá trị mà bạn muốn nó có.')
print('b. Tên biến hợp lệ: 1_st')
print('   Tên biến không hợp lệ: Hoá đơn')
print('c. Biến "day_per_years" để chỉ số ngày trong năm.')
print('d. Các cách đặt tên biến: -không/có hoa, không/có cách, không/có dấu')
print('e. Camel case là cách viết các cụm từ không có dấu cách hoặc dấu chấm câu. Nó chỉ ra sự phân tách các từ bằng một chữ cái viết hoa duy nhất và từ đầu tiên bắt đầu bằng một trong hai trường hợp. Các ví dụ phổ biến bao gồm " iPhone " và " eBay ".')
print('   Pascal case là cách viết hoa các chứ đầu, không có cách.')
print('   Snake case là cách viết không hoa, cách nhau bằng dấu "_".')
print('f. Camel case')