print("a)")
print("Ten bien khong duoc bat dau bang chu so")
print("Khong duoc dung cac ky hieu dang biet nhu !,@,#,%,...")
print("Khong duoc dat ten trung voi tu khoa")
print("b)")
print("Ten bien hop le: count,temp,a,...")
print("Ten bien khong hop le: 12abc, thang@,...")
print("c)")
print("Vi du ve cach dat ten bien tot:")
print("count: dung cho bien dem")
print("listOfPrimes: danh sach cac so nguyen to")
print("d)")
print("numberofcollegestudents: ten bien viet thuong toan bo")
print("NUMBEROFCOLLEGESTUDENTS: ten bien viet hoa toan bo")
print("numberOfCollegeStudents: phong cach Camel Case")
print("NumberOfCollegeStudents: phong cach Pascal Case")
print("number_of_college_students: phong cach Snake Case")
print("e)")
print("Camel Case: viet hoa cac chu cai dau tru tu dau tien")
print("Pascal Case: viet hoa tat ca cac chu cai dau tien")
print("Snake Case: cac tu cach nhau boi dau _")
print("f)")
print("Khi code em thuong dung phong cach Camel Case hoac Snake Case")