# -*- coding: utf-8 -*-
"""week01_assignment01_student46_NguyenTheSon.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hO2900LR1aKJHMY_OO_Apw8N3QM0Tgxn

Bài 1:
a) Ngôn ngữ lập trình được tạo ra bởi Guido van Rossum vào năm 1991 được coi như là hậu duệ của ngôn ngữ lập trình ABC.

b) Sở dĩ Guido van Rossum đặt tên là Python vì vào những năm 1970 tại Anh, có các tập phim hài "Monty Python's Flying Circus"
và Rossum chính là fan ruột của tập phim này nên ông đã lấy cái tên Python để đặt cho ngôn ngữ do chính ông tạo ra.

c)Tính tới ngày 13/07/2022, phiên bản Python mới nhất được phát hành là phiên bản 3.10.5.
"""